:config:
  :cookie:
    :key: 'rack.session'
    :path: '/'
  :live_reload:
    :min_delay:  500    # default 1000
    :max_delay:  10_000 # default 60_000
    :live_reload_port: 56789  # default 35729
    :host:  'localhost:3000'
    :ignore:
      -  !ruby/regexp '/.*\.html$/'
  :server:
    :handler: 'puma'
:envs:

